### ISSUE TITLE
Crash: MathKt__MathJVMKt.roundToInt (Cannot round NaN value.)

### ISSUE THREAD

**Issue by pflammertsma** [pflammertsma/cryptogram#79]
```
Fatal Exception: java.lang.IllegalArgumentException: Cannot round NaN value.
       at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:1132)
       at com.pixplicity.cryptogram.views.KeyboardButton$2.onTouch(KeyboardButton.kt:88)
       at android.view.View.dispatchTouchEvent(View.java:13426)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:465)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1849)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3993)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:423)
       at android.view.View.dispatchPointerEvent(View.java:13689)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5482)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5285)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4947)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5004)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7505)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7474)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7435)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7630)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:178)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7581)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7654)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
       at android.view.Choreographer.doCallbacks(Choreographer.java:790)
       at android.view.Choreographer.doFrame(Choreographer.java:718)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by pflammertsma** [comment]
Resolved in 321a751ce159c85f518b07478e7547a9b946b809
